// staticconstant.ts

const countries = [
    { cca2: 'IN', callingCode: ['91'], flag: '🇮🇳', name: 'India' },
    { cca2: 'AF', callingCode: ['93'], flag: '🇦🇫', name: 'Afghanistan' },
    { cca2: 'AL', callingCode: ['355'], flag: '🇦🇱', name: 'Albania' },
    { cca2: 'DZ', callingCode: ['213'], flag: '🇩🇿', name: 'Algeria' },
    { cca2: 'AS', callingCode: ['1'], flag: '🇦🇸', name: 'American Samoa' },
    { cca2: 'AD', callingCode: ['376'], flag: '🇦🇩', name: 'Andorra' },
    { cca2: 'AO', callingCode: ['244'], flag: '🇦🇴', name: 'Angola' },
    { cca2: 'AI', callingCode: ['1'], flag: '🇦🇮', name: 'Anguilla' },
    { cca2: 'AG', callingCode: ['1'], flag: '🇦🇬', name: 'Antigua and Barbuda' },
    { cca2: 'AR', callingCode: ['54'], flag: '🇦🇷', name: 'Argentina' },
    { cca2: 'AM', callingCode: ['374'], flag: '🇦🇲', name: 'Armenia' },
    { cca2: 'AU', callingCode: ['61'], flag: '🇦🇺', name: 'Australia' },
    { cca2: 'AT', callingCode: ['43'], flag: '🇦🇹', name: 'Austria' },
    { cca2: 'AZ', callingCode: ['994'], flag: '🇦🇿', name: 'Azerbaijan' },
    { cca2: 'BH', callingCode: ['973'], flag: '🇧🇭', name: 'Bahrain' },
    { cca2: 'BD', callingCode: ['880'], flag: '🇧🇩', name: 'Bangladesh' },
    { cca2: 'BY', callingCode: ['375'], flag: '🇧🇾', name: 'Belarus' },
    { cca2: 'BE', callingCode: ['32'], flag: '🇧🇪', name: 'Belgium' },
    { cca2: 'BZ', callingCode: ['501'], flag: '🇧🇿', name: 'Belize' },
    { cca2: 'BJ', callingCode: ['229'], flag: '🇧🇯', name: 'Benin' },
    { cca2: 'BT', callingCode: ['975'], flag: '🇧🇹', name: 'Bhutan' },
    { cca2: 'BO', callingCode: ['591'], flag: '🇧🇴', name: 'Bolivia' },
    {
      cca2: 'BA',
      callingCode: ['387'],
      flag: '🇧🇦',
      name: 'Bosnia and Herzegovina',
    },
    { cca2: 'BW', callingCode: ['267'], flag: '🇧🇼', name: 'Botswana' },
    { cca2: 'BR', callingCode: ['55'], flag: '🇧🇷', name: 'Brazil' },
    { cca2: 'BN', callingCode: ['673'], flag: '🇧🇳', name: 'Brunei' },
    { cca2: 'BG', callingCode: ['359'], flag: '🇧🇬', name: 'Bulgaria' },
    { cca2: 'KH', callingCode: ['855'], flag: '🇰🇭', name: 'Cambodia' },
    { cca2: 'CM', callingCode: ['237'], flag: '🇨🇲', name: 'Cameroon' },
    { cca2: 'CA', callingCode: ['1'], flag: '🇨🇦', name: 'Canada' },
    { cca2: 'CN', callingCode: ['86'], flag: '🇨🇳', name: 'China' },
    { cca2: 'CO', callingCode: ['57'], flag: '🇨🇴', name: 'Colombia' },
    { cca2: 'CU', callingCode: ['53'], flag: '🇨🇺', name: 'Cuba' },
    { cca2: 'DK', callingCode: ['45'], flag: '🇩🇰', name: 'Denmark' },
    { cca2: 'EG', callingCode: ['20'], flag: '🇪🇬', name: 'Egypt' },
    { cca2: 'FR', callingCode: ['33'], flag: '🇫🇷', name: 'France' },
    { cca2: 'DE', callingCode: ['49'], flag: '🇩🇪', name: 'Germany' },
    { cca2: 'GR', callingCode: ['30'], flag: '🇬🇷', name: 'Greece' },
    { cca2: 'HK', callingCode: ['852'], flag: '🇭🇰', name: 'Hong Kong' },
    { cca2: 'ID', callingCode: ['62'], flag: '🇮🇩', name: 'Indonesia' },
    { cca2: 'IR', callingCode: ['98'], flag: '🇮🇷', name: 'Iran' },
    { cca2: 'IQ', callingCode: ['964'], flag: '🇮🇶', name: 'Iraq' },
    { cca2: 'IE', callingCode: ['353'], flag: '🇮🇪', name: 'Ireland' },
    { cca2: 'IT', callingCode: ['39'], flag: '🇮🇹', name: 'Italy' },
    { cca2: 'JP', callingCode: ['81'], flag: '🇯🇵', name: 'Japan' },
    { cca2: 'KR', callingCode: ['82'], flag: '🇰🇷', name: 'South Korea' },
    { cca2: 'MY', callingCode: ['60'], flag: '🇲🇾', name: 'Malaysia' },
    { cca2: 'MX', callingCode: ['52'], flag: '🇲🇽', name: 'Mexico' },
    { cca2: 'NL', callingCode: ['31'], flag: '🇳🇱', name: 'Netherlands' },
    { cca2: 'NZ', callingCode: ['64'], flag: '🇳🇿', name: 'New Zealand' },
    { cca2: 'NG', callingCode: ['234'], flag: '🇳🇬', name: 'Nigeria' },
    { cca2: 'PK', callingCode: ['92'], flag: '🇵🇰', name: 'Pakistan' },
    { cca2: 'PH', callingCode: ['63'], flag: '🇵🇭', name: 'Philippines' },
    { cca2: 'RU', callingCode: ['7'], flag: '🇷🇺', name: 'Russia' },
    { cca2: 'SA', callingCode: ['966'], flag: '🇸🇦', name: 'Saudi Arabia' },
    { cca2: 'ZA', callingCode: ['27'], flag: '🇿🇦', name: 'South Africa' },
    { cca2: 'ES', callingCode: ['34'], flag: '🇪🇸', name: 'Spain' },
    { cca2: 'SE', callingCode: ['46'], flag: '🇸🇪', name: 'Sweden' },
    { cca2: 'CH', callingCode: ['41'], flag: '🇨🇭', name: 'Switzerland' },
    { cca2: 'TH', callingCode: ['66'], flag: '🇹🇭', name: 'Thailand' },
    { cca2: 'TR', callingCode: ['90'], flag: '🇹🇷', name: 'Turkey' },
    { cca2: 'UA', callingCode: ['380'], flag: '🇺🇦', name: 'Ukraine' },
    { cca2: 'AE', callingCode: ['971'], flag: '🇦🇪', name: 'United Arab Emirates' },
    { cca2: 'GB', callingCode: ['44'], flag: '🇬🇧', name: 'United Kingdom' },
    { cca2: 'US', callingCode: ['1'], flag: '🇺🇸', name: 'United States' },
    { cca2: 'VN', callingCode: ['84'], flag: '🇻🇳', name: 'Vietnam' },
  ];
  
  export default countries;  // Exporting the countries array