[build]
  command = "gem update --system && gem install bundler && gem install ffi && yarn install && yarn build"
  publish = "build"  # Folder to be published

[build.environment]
  RUBY_VERSION = "2.7.2"  # Ruby version
  RUBYGEMS_VERSION = "3.3.22"  # RubyGems version
  NODE_VERSION = "18"  # Node.js version
  YARN_VERSION = "1.x"  # Yarn version
