[build]
  command = "yarn install && yarn build"  # Keep the simplified build command
  publish = "build"  # Make sure the output folder is correct

[build.environment]
  NODE_VERSION = "18"  # Enforce Node.js version 18 (or adjust to your preferred version)
  YARN_VERSION = "1.x"  # Ensure Yarn version 1.x is used, if applicable

  # Optional: Add any other environment variables you may need here
  # Example: REACT_APP_API_URL = "https://your-api-url"
