[build]
  command = "yarn install && yarn build"  # Install dependencies and build the app using Yarn
  publish = "build"  # The folder where the built app is located, typically 'build'

[build.environment]
  NODE_ENV = "production"  # Ensure you're in production mode for optimization

